Fixes git-publish on Windows.
The NamedTemporaryFile can not be opened by other editor. so we use
tempfile.mkstemp(text=True) instead.

[c] Edit Cc list in editor (save after edit)
[t] Edit To list in editor (save after edit)
[e] Edit patches in editor
[s] Select patches to send (default: all)
[p] Print final email headers (dry run)
[a] Send all
[q] Cancel (quit)
s
Traceback (most recent call last):
  File "git-publish.py", line 905, in <module>
    sys.exit(main())
  File "git-publish.py", line 862, in main
    selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
  File "git-publish.py", line 514, in inspect_menu
    listfile.write("\n".join(patches).encode(ENCODING))
TypeError: sequence item 0: expected str instance, bytes found

The notepad.exe complains
The other program are using this file, the process can not access it.

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>